export const products = [
  {
    id: 1,
    name: "Training Soccer Ball",
    category: "Sports",
    price: 58.03,
    rating: 4.8,
    status: "avaiable",
  },
  {
    id: 2,
    name: "Eco-Friendly Yoga Blocks",
    category: "Fitness",
    price: 81.02,
    rating: 4.7,
    status: "client",
  },
  {
    id: 3,
    name: "Garlic Herb Marinade",
    category: "Food - Marinades",
    price: 99.37,
    rating: 4.5,
    status: "avaiable",
  },
  {
    id: 4,
    name: "Lightweight Backpacking Tent",
    category: "Outdoor",
    price: 60.91,
    rating: 4.9,
    status: "service",
  },
  {
    id: 5,
    name: "Heated Throw Blanket",
    category: "Home",
    price: 70.32,
    rating: 4.9,
    status: "avaiable",
  },
  {
    id: 6,
    name: "Pepperoni Pizza Roll-Ups",
    category: "Food - Frozen Foods",
    price: 131.02,
    rating: 5.0,
    status: "client",
  },
  {
    id: 7,
    name: "Faux Fur Throw Blanket",
    category: "Home",
    price: 66.12,
    rating: 4.8,
    status: "avaiable",
  },
  {
    id: 8,
    name: "Karaoke Microphone",
    category: "Music",
    price: 35.63,
    rating: 4.4,
    status: "service",
  },
  {
    id: 9,
    name: "Cooking Utensil Set",
    category: "Kitchen",
    price: 116.78,
    rating: 4.0,
    status: "avaiable",
  },
  {
    id: 10,
    name: "LED Under Cabinet Lighting",
    category: "Home",
    price: 84.84,
    rating: 4.8,
    status: "avaiable",
  },
  {
    id: 11,
    name: "Pet Activity Tracker",
    category: "Pets",
    price: 138.0,
    rating: 5.0,
    status: "removed",
  },
  {
    id: 12,
    name: "Spaghetti Squash",
    category: "Food - Produce",
    price: 42.03,
    rating: 4.7,
    status: "avaiable",
  },
  {
    id: 13,
    name: "Cabbage Slaw Mix",
    category: "Food - Vegetables",
    price: 133.17,
    rating: 4.9,
    status: "avaiable",
  },
  {
    id: 14,
    name: "Glass Tea Pot",
    category: "Kitchen",
    price: 44.73,
    rating: 4.8,
    status: "avaiable",
  }
];
